import type { Metadata } from "next";
import ClientHeader from "@/components/layout/header/ClientHeader";
import ClientFooter from "@/components/layout/footer/ClientFooter";
import PageTransitionWrapper from "@/components/layout/common/PageTransitionWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <ClientHeader />
      <PageTransitionWrapper>{children}</PageTransitionWrapper>
      <ClientFooter />
    </>
  );
}
