import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ClientHeader from "@/components/layout/header/ClientHeader";
import "../../app/globals.css";
import ClientFooter from "@/components/layout/footer/ClientFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
        style={{ height: "100vh" }}
        cz-shortcut-listen="true"
      >
        {/* Header - Sticky */}
        <header className="sticky top-0 z-50 bg-white border-b flex-shrink-0">
          <ClientHeader />
        </header>

        {/* Content - scroll trong main */}
        <main className="flex-grow overflow-y-auto">
          {children}
        </main>

        {/* Footer - Sticky bottom */}
        <ClientFooter />
      </body>
    </html>
  );
}
